language: node_js
node_js:
- '6.6'
install:
- npm install
script:
- npm test
- npm run build
after_success: npm run coverage
notifications:
  slack: teamtaverna:iP55LweubU8UOBgu9e0cTeED
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: rC+e4C8+apNPmi70U1A6b6fr/6sCrw+esirDLpSk6QUAgQpIH1OLvKbgg7cpNSakcmY9xzb1EDIZAu613WnSH/j36NOgT2QPs3zF9fzvHNwMG8JXwUaAURMKdaAgwmpc0yET7avE9Jccfxpr3AG48FQZhQjqJ7IXPXzNRK/nIFah3AaYgNkbxnEAAU7es2ufWm2aPpghEU/XE7F/AJNowNc0nSTZZ3/Cez1m3XMJpdGwlP9UN+F5ApRxhw6mGmSecg41vc4yI9HP1V44TejolXUC9T+3/U4Ui4l4ClnUxqZbgRtXLAmHN61nBIlF10CLha5uHuTzwU7Yq5adPQuJ+2Hx3XwTBiehRq5Lkg7wyef4JbiUbr8nUm2gfWbOfPl2oaaoWVsIA/4/9j6R3nv51kKt4hD4DU7MsfOoVbodmqb2sPHHZPanx/+dgGMtoFwR5XeaYlWT04SkVuel3koJ9DQHGLjcPIg6GXiVgvrjtF9+4mjEzscbLaRQEMEm4kKga0kSlGf7yaSg91IvIWM3fCs82ahueHW3HfhuzIT+mztXBs4L4eKQ0Tz1Y/YlnTr1RWY6myqeYEv8Cd6WPXs4XbRR8joR8MVNq9vsjYxiL8QSTTipYG+Cns+d9OxhT+f3zO00gwMnTfOdaQ8Hks2USjTA6hO6CQmhbenQXv6ZL2U=
  app:
    master: taverna-webclient
    branch-test: tarvena-deploy-test
